"""
Train Autoencoder anomaly detection model for credit card fraud detection.

This script uses the official processed train/test split generated by:

python src/preprocess.py --input data/raw/creditcard.csv --output data/processed

Important:
- This script does not create a new train/test split.
- Autoencoder uses scaled features.
- The model is trained only on non-fraud training transactions.
- Fraud is detected using reconstruction error.
"""

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPRegressor

from evaluation import evaluate_model_performance, save_metrics_to_report


RANDOM_STATE = 42


def load_official_scaled_split(input_dir: Path):
    """
    Load official scaled train/test split.

    Args:
        input_dir: Folder containing processed split files.

    Returns:
        X_train_scaled, X_test_scaled, y_train, y_test
    """
    X_train = pd.read_csv(input_dir / "X_train_scaled.csv")
    X_test = pd.read_csv(input_dir / "X_test_scaled.csv")
    y_train = pd.read_csv(input_dir / "y_train.csv").squeeze("columns")
    y_test = pd.read_csv(input_dir / "y_test.csv").squeeze("columns")

    return X_train, X_test, y_train, y_test


def train_autoencoder(X_train_normal: pd.DataFrame) -> MLPRegressor:
    """
    Train an Autoencoder-style neural network using MLPRegressor.

    Args:
        X_train_normal: Non-fraud training features only.

    Returns:
        Trained reconstruction model.
    """
    model = MLPRegressor(
        hidden_layer_sizes=(16, 8, 16),
        activation="relu",
        solver="adam",
        alpha=0.0001,
        learning_rate_init=0.001,
        max_iter=100,
        random_state=RANDOM_STATE,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=10,
        verbose=True,
    )

    model.fit(X_train_normal, X_train_normal)

    return model


def calculate_reconstruction_error(model, X: pd.DataFrame) -> np.ndarray:
    """
    Calculate reconstruction error for each transaction.

    Args:
        model: Trained Autoencoder model.
        X: Input features.

    Returns:
        Mean squared reconstruction error per row.
    """
    reconstructed = model.predict(X)
    errors = np.mean(np.square(X.values - reconstructed), axis=1)

    return errors


def select_threshold(train_errors: np.ndarray, percentile: float = 99.5) -> float:
    """
    Select anomaly threshold from training reconstruction errors.

    Args:
        train_errors: Reconstruction errors from normal training transactions.
        percentile: Percentile threshold.

    Returns:
        Threshold value.
    """
    threshold = np.percentile(train_errors, percentile)
    return threshold


def evaluate_autoencoder(y_test, test_errors, threshold: float) -> dict:
    """
    Evaluate Autoencoder anomaly detection performance.

    Args:
        y_test: True test labels.
        test_errors: Reconstruction error scores for test set.
        threshold: Fraud classification threshold.

    Returns:
        Dictionary of evaluation results.
    """
    y_pred = (test_errors >= threshold).astype(int)

    metrics = evaluate_model_performance(
        y_true=y_test,
        y_pred=y_pred,
        y_pred_proba=test_errors,
    )

    cm = confusion_matrix(y_test, y_pred)

    results = {
        "threshold_strategy": "training_normal_reconstruction_error_percentile",
        "threshold_percentile": 99.5,
        "threshold": float(threshold),
        "accuracy": float(metrics["accuracy"]),
        "precision": float(metrics["precision"]),
        "recall": float(metrics["recall"]),
        "f1_score": float(metrics["f1_score"]),
        "roc_auc": float(metrics["roc_auc"]),
        "pr_auc": float(metrics["pr_auc"]),
        "confusion_matrix": {
            "true_negative": int(cm[0, 0]),
            "false_positive": int(cm[0, 1]),
            "false_negative": int(cm[1, 0]),
            "true_positive": int(cm[1, 1]),
        },
    }

    return results


def threshold_tuning(y_test, test_errors) -> pd.DataFrame:
    """
    Evaluate Autoencoder performance across threshold percentiles.

    Args:
        y_test: True test labels.
        test_errors: Test reconstruction errors.

    Returns:
        DataFrame with threshold performance results.
    """
    rows = []

    for percentile in [95.0, 97.0, 98.0, 99.0, 99.5, 99.7, 99.9]:
        threshold = np.percentile(test_errors, percentile)
        y_pred = (test_errors >= threshold).astype(int)

        metrics = evaluate_model_performance(
            y_true=y_test,
            y_pred=y_pred,
            y_pred_proba=test_errors,
        )

        cm = confusion_matrix(y_test, y_pred)

        rows.append(
            {
                "threshold_percentile_on_test_errors": percentile,
                "threshold": threshold,
                "accuracy": metrics["accuracy"],
                "precision": metrics["precision"],
                "recall": metrics["recall"],
                "f1_score": metrics["f1_score"],
                "roc_auc": metrics["roc_auc"],
                "pr_auc": metrics["pr_auc"],
                "false_positive": int(cm[0, 1]),
                "false_negative": int(cm[1, 0]),
                "true_positive": int(cm[1, 1]),
                "true_negative": int(cm[0, 0]),
            }
        )

    return pd.DataFrame(rows)


def save_outputs(
    model,
    results: dict,
    threshold_results: pd.DataFrame,
    output_dir: Path,
    report_dir: Path,
) -> None:
    """
    Save Autoencoder model and reports.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    joblib.dump(model, output_dir / "autoencoder_fraud_model.joblib")

    with open(report_dir / "autoencoder_results.json", "w", encoding="utf-8") as file:
        json.dump(results, file, indent=4)

    threshold_results.to_csv(report_dir / "autoencoder_threshold_results.csv", index=False)

    save_metrics_to_report(
        metrics_dict={
            "accuracy": results["accuracy"],
            "precision": results["precision"],
            "recall": results["recall"],
            "f1_score": results["f1_score"],
            "roc_auc": results["roc_auc"],
            "pr_auc": results["pr_auc"],
        },
        file_path=report_dir / "metrics_summary.csv",
        model_name="Autoencoder",
    )

    print(f"Model saved to: {output_dir / 'autoencoder_fraud_model.joblib'}")
    print(f"Results saved to: {report_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train Autoencoder anomaly detection model.")
    parser.add_argument(
        "--input",
        type=str,
        default="data/processed",
        help="Directory containing official processed split files.",
    )
    parser.add_argument(
        "--model-output",
        type=str,
        default="model_artifacts",
        help="Directory to save model artifacts.",
    )
    parser.add_argument(
        "--report-output",
        type=str,
        default="reports",
        help="Directory to save model reports.",
    )
    parser.add_argument(
        "--threshold-percentile",
        type=float,
        default=99.5,
        help="Percentile of normal training reconstruction errors used as anomaly threshold.",
    )

    args = parser.parse_args()

    input_dir = Path(args.input)
    model_output_dir = Path(args.model_output)
    report_output_dir = Path(args.report_output)

    print("Loading official scaled processed split...")
    X_train, X_test, y_train, y_test = load_official_scaled_split(input_dir)

    print(f"X_train_scaled shape: {X_train.shape}")
    print(f"X_test_scaled shape: {X_test.shape}")
    print(f"y_train fraud count: {int(y_train.sum())}")
    print(f"y_test fraud count: {int(y_test.sum())}")

    X_train_normal = X_train[y_train == 0]

    print(f"Training Autoencoder on normal transactions only: {X_train_normal.shape}")

    model = train_autoencoder(X_train_normal)

    print("Calculating reconstruction errors...")
    train_normal_errors = calculate_reconstruction_error(model, X_train_normal)
    test_errors = calculate_reconstruction_error(model, X_test)

    threshold = select_threshold(
        train_errors=train_normal_errors,
        percentile=args.threshold_percentile,
    )

    print(f"Selected threshold percentile: {args.threshold_percentile}")
    print(f"Selected reconstruction error threshold: {threshold}")

    print("Evaluating Autoencoder...")
    results = evaluate_autoencoder(y_test, test_errors, threshold)

    print("\nAutoencoder Results")
    print("-------------------")
    print(json.dumps(results, indent=4))

    print("Running threshold tuning...")
    threshold_results = threshold_tuning(y_test, test_errors)
    print(threshold_results)

    save_outputs(
        model=model,
        results=results,
        threshold_results=threshold_results,
        output_dir=model_output_dir,
        report_dir=report_output_dir,
    )

    print("Autoencoder training pipeline completed successfully.")


if __name__ == "__main__":
    main()