"""
Train Logistic Regression baseline model for credit card fraud detection.

This script uses the official processed train/test split generated by:

python src/preprocess.py --input data/raw/creditcard.csv --output data/processed

Important:
- This script does not create a new train/test split.
- It uses scaled features because Logistic Regression is scale-sensitive.
- It uses class_weight="balanced" to handle class imbalance.
- It uses shared evaluation.py for standardized reporting.
"""

import argparse
import json
from pathlib import Path

import joblib
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

from evaluation import evaluate_model_performance, save_metrics_to_report


RANDOM_STATE = 42


def load_official_scaled_split(input_dir: Path):
    """
    Load official scaled train/test split.

    Args:
        input_dir: Folder containing processed split files.

    Returns:
        X_train, X_test, y_train, y_test
    """
    X_train = pd.read_csv(input_dir / "X_train_scaled.csv")
    X_test = pd.read_csv(input_dir / "X_test_scaled.csv")
    y_train = pd.read_csv(input_dir / "y_train.csv").squeeze("columns")
    y_test = pd.read_csv(input_dir / "y_test.csv").squeeze("columns")

    return X_train, X_test, y_train, y_test


def train_model(X_train, y_train) -> LogisticRegression:
    """
    Train Logistic Regression baseline model.
    """
    model = LogisticRegression(
        class_weight="balanced",
        random_state=RANDOM_STATE,
        max_iter=1000,
        n_jobs=-1,
    )

    model.fit(X_train, y_train)

    return model


def evaluate_baseline(model, X_test, y_test, threshold: float = 0.50) -> dict:
    """
    Evaluate Logistic Regression baseline using shared evaluation utility.
    """
    y_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_proba >= threshold).astype(int)

    metrics = evaluate_model_performance(
        y_true=y_test,
        y_pred=y_pred,
        y_pred_proba=y_proba,
    )

    cm = confusion_matrix(y_test, y_pred)

    results = {
        "threshold": threshold,
        "accuracy": float(metrics["accuracy"]),
        "precision": float(metrics["precision"]),
        "recall": float(metrics["recall"]),
        "f1_score": float(metrics["f1_score"]),
        "roc_auc": float(metrics["roc_auc"]),
        "pr_auc": float(metrics["pr_auc"]),
        "confusion_matrix": {
            "true_negative": int(cm[0, 0]),
            "false_positive": int(cm[0, 1]),
            "false_negative": int(cm[1, 0]),
            "true_positive": int(cm[1, 1]),
        },
    }

    return results


def save_outputs(model, results: dict, model_output_dir: Path, report_output_dir: Path) -> None:
    """
    Save model artifact and report outputs.
    """
    model_output_dir.mkdir(parents=True, exist_ok=True)
    report_output_dir.mkdir(parents=True, exist_ok=True)

    joblib.dump(model, model_output_dir / "logistic_baseline_model.joblib")

    with open(report_output_dir / "logistic_baseline_results.json", "w", encoding="utf-8") as file:
        json.dump(results, file, indent=4)

    save_metrics_to_report(
        metrics_dict={
            "accuracy": results["accuracy"],
            "precision": results["precision"],
            "recall": results["recall"],
            "f1_score": results["f1_score"],
            "roc_auc": results["roc_auc"],
            "pr_auc": results["pr_auc"],
        },
        file_path=report_output_dir / "metrics_summary.csv",
        model_name="Logistic Regression Baseline",
    )

    print(f"Model saved to: {model_output_dir / 'logistic_baseline_model.joblib'}")
    print(f"Results saved to: {report_output_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train Logistic Regression baseline model.")
    parser.add_argument(
        "--input",
        type=str,
        default="data/processed",
        help="Directory containing official processed split files.",
    )
    parser.add_argument(
        "--model-output",
        type=str,
        default="model_artifacts",
        help="Directory to save model artifacts.",
    )
    parser.add_argument(
        "--report-output",
        type=str,
        default="reports",
        help="Directory to save model reports.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.50,
        help="Classification threshold.",
    )

    args = parser.parse_args()

    input_dir = Path(args.input)
    model_output_dir = Path(args.model_output)
    report_output_dir = Path(args.report_output)

    print("Loading official scaled processed split...")
    X_train, X_test, y_train, y_test = load_official_scaled_split(input_dir)

    print(f"X_train_scaled shape: {X_train.shape}")
    print(f"X_test_scaled shape: {X_test.shape}")
    print(f"y_train fraud count: {int(y_train.sum())}")
    print(f"y_test fraud count: {int(y_test.sum())}")

    print("Training Logistic Regression baseline...")
    model = train_model(X_train, y_train)

    print("Evaluating Logistic Regression baseline...")
    results = evaluate_baseline(model, X_test, y_test, threshold=args.threshold)

    print("\nLogistic Regression Baseline Results")
    print("------------------------------------")
    print(json.dumps(results, indent=4))

    save_outputs(
        model=model,
        results=results,
        model_output_dir=model_output_dir,
        report_output_dir=report_output_dir,
    )

    print("Logistic Regression baseline pipeline completed successfully.")


if __name__ == "__main__":
    main()