"""
Train XGBoost supervised classification model for credit card fraud detection.

This script uses the official processed train/test split generated by:

python src/preprocess.py --input data/raw/creditcard.csv --output data/processed

Important:
- This script does not create a new train/test split.
- This ensures fair comparison with baseline and Autoencoder models.
- XGBoost uses the unscaled split because tree-based models do not require scaling.
"""

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from xgboost import XGBClassifier


RANDOM_STATE = 42


def load_official_split(input_dir: Path):
    """
    Load official processed train/test split.

    Args:
        input_dir: Folder containing processed split files.

    Returns:
        X_train, X_test, y_train, y_test
    """
    X_train = pd.read_csv(input_dir / "X_train.csv")
    X_test = pd.read_csv(input_dir / "X_test.csv")
    y_train = pd.read_csv(input_dir / "y_train.csv").squeeze("columns")
    y_test = pd.read_csv(input_dir / "y_test.csv").squeeze("columns")

    return X_train, X_test, y_train, y_test


def calculate_scale_pos_weight(y_train: pd.Series) -> float:
    """
    Calculate imbalance weight for XGBoost.

    Args:
        y_train: Training target labels.

    Returns:
        scale_pos_weight value.
    """
    non_fraud_count = int((y_train == 0).sum())
    fraud_count = int((y_train == 1).sum())

    if fraud_count == 0:
        raise ValueError("No fraud cases found in y_train.")

    return non_fraud_count / fraud_count


def train_model(X_train, y_train, scale_pos_weight: float) -> XGBClassifier:
    """
    Train XGBoost model.

    Args:
        X_train: Training features.
        y_train: Training labels.
        scale_pos_weight: Class imbalance weight.

    Returns:
        Trained XGBoost model.
    """
    model = XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="aucpr",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(X_train, y_train)

    return model


def evaluate_model(model, X_test, y_test, threshold: float = 0.50) -> dict:
    """
    Evaluate XGBoost model.

    Args:
        model: Trained model.
        X_test: Test features.
        y_test: Test labels.
        threshold: Classification probability threshold.

    Returns:
        Dictionary of evaluation results.
    """
    y_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_proba >= threshold).astype(int)

    cm = confusion_matrix(y_test, y_pred)

    results = {
        "threshold": threshold,
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred, zero_division=0)),
        "f1_score": float(f1_score(y_test, y_pred, zero_division=0)),
        "roc_auc": float(roc_auc_score(y_test, y_proba)),
        "pr_auc": float(average_precision_score(y_test, y_proba)),
        "confusion_matrix": {
            "true_negative": int(cm[0, 0]),
            "false_positive": int(cm[0, 1]),
            "false_negative": int(cm[1, 0]),
            "true_positive": int(cm[1, 1]),
        },
    }

    return results


def threshold_tuning(model, X_test, y_test) -> pd.DataFrame:
    """
    Evaluate performance across multiple thresholds.

    Args:
        model: Trained model.
        X_test: Test features.
        y_test: Test labels.

    Returns:
        DataFrame with threshold performance results.
    """
    y_proba = model.predict_proba(X_test)[:, 1]

    threshold_values = [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90]
    rows = []

    for threshold in threshold_values:
        y_pred = (y_proba >= threshold).astype(int)
        cm = confusion_matrix(y_test, y_pred)

        rows.append(
            {
                "threshold": threshold,
                "precision": precision_score(y_test, y_pred, zero_division=0),
                "recall": recall_score(y_test, y_pred, zero_division=0),
                "f1_score": f1_score(y_test, y_pred, zero_division=0),
                "false_positive": int(cm[0, 1]),
                "false_negative": int(cm[1, 0]),
                "true_positive": int(cm[1, 1]),
                "true_negative": int(cm[0, 0]),
            }
        )

    return pd.DataFrame(rows)


def save_outputs(
    model,
    X_train,
    results: dict,
    threshold_results: pd.DataFrame,
    output_dir: Path,
    report_dir: Path,
) -> None:
    """
    Save model artifact and report outputs.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    joblib.dump(model, output_dir / "xgboost_fraud_model.joblib")

    with open(report_dir / "xgboost_results.json", "w", encoding="utf-8") as file:
        json.dump(results, file, indent=4)

    threshold_results.to_csv(report_dir / "xgboost_threshold_results.csv", index=False)

    feature_importance = pd.DataFrame(
        {
            "feature": X_train.columns,
            "importance": model.feature_importances_,
        }
    ).sort_values("importance", ascending=False)

    feature_importance.to_csv(report_dir / "xgboost_feature_importance.csv", index=False)

    print(f"Model saved to: {output_dir / 'xgboost_fraud_model.joblib'}")
    print(f"Results saved to: {report_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train XGBoost fraud detection model.")
    parser.add_argument(
        "--input",
        type=str,
        default="data/processed",
        help="Directory containing official processed split files.",
    )
    parser.add_argument(
        "--model-output",
        type=str,
        default="model_artifacts",
        help="Directory to save model artifacts.",
    )
    parser.add_argument(
        "--report-output",
        type=str,
        default="reports",
        help="Directory to save model reports.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.50,
        help="Classification threshold.",
    )

    args = parser.parse_args()

    input_dir = Path(args.input)
    model_output_dir = Path(args.model_output)
    report_output_dir = Path(args.report_output)

    print("Loading official processed split...")
    X_train, X_test, y_train, y_test = load_official_split(input_dir)

    print(f"X_train shape: {X_train.shape}")
    print(f"X_test shape: {X_test.shape}")
    print(f"y_train fraud count: {int(y_train.sum())}")
    print(f"y_test fraud count: {int(y_test.sum())}")

    scale_pos_weight = calculate_scale_pos_weight(y_train)
    print(f"scale_pos_weight: {scale_pos_weight:.4f}")

    print("Training XGBoost model...")
    model = train_model(X_train, y_train, scale_pos_weight)

    print("Evaluating XGBoost model...")
    results = evaluate_model(model, X_test, y_test, threshold=args.threshold)

    print("\nXGBoost Results")
    print("----------------")
    print(json.dumps(results, indent=4))

    print("\nClassification Report")
    y_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_proba >= args.threshold).astype(int)
    print(classification_report(y_test, y_pred, target_names=["Non-Fraud", "Fraud"]))

    print("Running threshold tuning...")
    threshold_results = threshold_tuning(model, X_test, y_test)
    print(threshold_results)

    save_outputs(
        model=model,
        X_train=X_train,
        results=results,
        threshold_results=threshold_results,
        output_dir=model_output_dir,
        report_dir=report_output_dir,
    )

    print("XGBoost training pipeline completed successfully.")


if __name__ == "__main__":
    main()